"""add patient diseases

Revision ID: 501cf0cf9151
Revises: b2c3d4e5f6a7
Create Date: 2026-06-27 19:39:43.429950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501cf0cf9151'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('variant', sa.Enum('green', 'purple', 'red', 'blue', 'yellow', 'orange', name='disease_tag_variant'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_diseases_patient_id'), 'patient_diseases', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_patients_iin'), table_name='patients')
    op.create_unique_constraint(None, 'patients', ['iin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_index(op.f('ix_patients_iin'), 'patients', ['iin'], unique=True)
    op.drop_index(op.f('ix_patient_diseases_patient_id'), table_name='patient_diseases')
    op.drop_table('patient_diseases')
    # ### end Alembic commands ###
