"""add vaccinations and hospitalizations

Revision ID: 7bbc5b3e4129
Revises: 290f3b051835
Create Date: 2026-06-27 20:08:58.075593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbc5b3e4129'
down_revision: Union[str, Sequence[str], None] = '290f3b051835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitalizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('bed', sa.String(length=50), nullable=True),
    sa.Column('admitted_at', sa.Date(), nullable=False),
    sa.Column('primary_diagnosis', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitalizations_doctor_id'), 'hospitalizations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_hospitalizations_patient_id'), 'hospitalizations', ['patient_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dose', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_patient_id'), 'vaccinations', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccinations_patient_id'), table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_hospitalizations_patient_id'), table_name='hospitalizations')
    op.drop_index(op.f('ix_hospitalizations_doctor_id'), table_name='hospitalizations')
    op.drop_table('hospitalizations')
    # ### end Alembic commands ###
