"""add prescriptions and schedules

Revision ID: 95c1f7da17f6
Revises: 7bbc5b3e4129
Create Date: 2026-06-27 20:32:12.634681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c1f7da17f6'
down_revision: Union[str, Sequence[str], None] = '7bbc5b3e4129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('start', sa.String(length=10), nullable=False),
    sa.Column('end', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_doctor_id'), 'schedules', ['doctor_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('medication', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=200), nullable=False),
    sa.Column('frequency', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_appointment_id'), 'prescriptions', ['appointment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_appointment_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_schedules_doctor_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
